#!/bin/bash

set -e

[[ "$#" != "1" ]] && exit 1

. /etc/docklet/docklet.conf

[[ "$@" == "" ]] && exit 1

CPU_ACCT="`cat /sys/fs/cgroup/cpuacct/lxc/$@/cpuacct.usage 2>/dev/null`"
[[ "${CPU_ACCT}" == "" ]] && exit 1

MEM_USAGE="`cat /sys/fs/cgroup/memory/lxc/$@/memory.usage_in_bytes 2>/dev/null`"
[[ "${MEM_USAGE}" == "" ]] && exit 1

echo -e "${CPU_ACCT}\n${MEM_USAGE}"

